dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  provider: heroku
  app: articuno-postproc
  strategy: git
  on: postproc-deployment
  api_key:
    secure: RU8hgpt5GQSey5/+4izplDpD5rR3OPn6Uz9jy/rKfF16NNMkY/fVFdSLbYN8a50vF3IHhWpVsrLJcqc521Xj0eWGrwgs8Zzpa5Pxd0lFpsndqTIWuH4zfXI170Y+u1nY2DBhzuTq3ewqLJ7QDjdKA0+5He/9LzQFqxluTPjQ7rolbNxvGmU+2c09PG2Ja2vlVWNQBFU1H+7EjFB80V/haxjjXNSOHZFnQU0b+lK6TDxSLjvn5qsLSaLevpcbxujD1TxPhATZnQekwtR/c4oiZK65XNs+sLeyXoRpUxTEk1XKI+Td+41s8kes8wDoXtoaoJPlub3vjT0H9NjAp9CE7LARaMYcppaKWrVrYIstVp4ytnagHMiu2UacBsTBa654zJUZ31gUJ2rSF1a78cnmufeehRiGGLhyv8MPx9ShZAhd8uNN58s3voKHnatEyjrjP5Z23y23csETzZImR3SCMRM1TEy7ZOIjPG/6Xib0+YmtC6ixVHV9+2s5Jv/1XeTXZXIhv/Ww4sks/zj3ipOcchgLp+rfPUNWdOUTO/5belBba1LAQ2hkPs56HppfrjaSprFOexFEWnOFsXmm2uOa8caYN7XwDl76M80QW4VaAXlucO92Wwj55rxhmFXYsB2IBXKI+3n7cEeDi7XcvqmZeUFyFate4zQ9Hb6NF46BWTM=
